export const categoryOptions = [
  'Metal',
  'Wood',
  'Plastic',
  'Equipment (W/H)',
  'Consumable (W/H)',
  'IT Equipment',
  'Safety Equipments',
  'Miscellaneous Items',
  'FLC',
  'FLC Insert',
  'FLC Separator sheet',
  'FSC',
  'FSC Separator sheet',
  'Crate',
  'Crate Insert',
  'Crate Separator Sheet',
  'Wire Mesh Insert',
  'Shipper',
  'Office Equipment',
  'Other',
];
